### ISSUE TITLE
line indent breaks Spoiler Blocks

### ISSUE THREAD

**Issue by PackElend** [martinkorelic/joplin-plugin-spoilers#11]
Hi,
thx for the great plug-in. I have recently started to intense its use and noted the following

If I work with indents, the spoiler does not include anything between `:[ ]:`

- expected, indented Spoiler Block
![image](https://user-images.githubusercontent.com/3542031/201603954-265d18b2-d261-47f9-80e7-bcd19a1e5a89.png)

- what it does 
  - second bullet point is not part of block `]:` is ignored
  ![image](https://user-images.githubusercontent.com/3542031/201604494-4025c796-44a8-434e-a788-2c64bca04407.png)

  - strange nesting:
  ![image](https://user-images.githubusercontent.com/3542031/201603464-cb2e9d0e-221d-412d-bbf3-7b2456532613.png)

**Comment by Mick2nd** [comment]
Hi,

I believe, this issue is also solved by the correct nesting fix.( #10 )

See the following screen shot. 

<img width="1046" alt="Spoiler with Bullet" src="https://user-images.githubusercontent.com/16988757/201689495-bd850bc0-c826-4860-88a1-3b25b067072f.png">

What I did not try with bullet: nested spoilers.

For the spoiler inside the task item to work correctly, please indent the whole block!

**Comment by PackElend** [comment]
> I believe, this issue is also solved by the correct nesting fix.( #10 )

why you don't do a Pull Request to get it merge in the code?


> For the spoiler inside the task item to work correctly, please indent the whole block!
I tried many combinations, three spaces works if it block is below a bullet point or to-do

```
## test
1. test 
   :[
   Title
   
   1. point
   2. point
   
   ]:
```
![image](https://user-images.githubusercontent.com/3542031/201836814-f66bf998-fafa-48d5-9891-0ce079eaaa74.png)

but without that, e.g. only heading there is not any indent 

```
## test
1. test 
   :[
   Title
   
   1. point
   2. point
   
   ]:


...some text
   :[
   Title
   
   1. point
   2. point
   
   ]:
```
![image](https://user-images.githubusercontent.com/3542031/201837507-4320e93d-59ad-4160-ada4-114cde0172d4.png)


so second would be resolved by your fix?

**Comment by Mick2nd** [comment]
Hi, I just did a pull request, so the author of Spoilers can integrate the change.

I believe, with the indentation there is nothing to fix as this is normal **MD** behavior: normal indented content does not appear indented in the rendered pane. The indentation of bullet or task items (or citations) is a different case.

Anyway, I don't want to spend too much time on this. That is a matter of the author.

**Comment by PackElend** [comment]
alright that is ok, we can close it.
We have a PR,  so all fine :)
